# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py
  
formats:
   - pdf

python:
  version: 3.8
  install:
    - requirements: requirements.txt